name: 'run-rf-tests'
on: [push]
jobs:
    run_tests:
      runs-on: ubuntu-latest
      name: Execute tests and publish test results
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Run tests
          uses: ./tests
        - name: 'Push test results'
          uses: actions/upload-artifact@v2
          with:
            name: test-results
            path: logs/
    archive_test_results:
      runs-on: ubuntu-latest
      name: Archive test result
      needs: run_tests
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: 'Download test results'
          uses: actions/download-artifact@v1
          with:
            name: test-results
        - name: 'Archive test results'
          uses: ./archiver
          env:
            TEAM:           github_action
            REPORT_FORMAT:  robotframework
            SERIES:         gha_test
            LOG_DIR:        ./test-results
            ARCHIVER_DB_ENGINE:    postgresql
            ARCHIVER_DB_NAME:     ${{ secrets.ARCHIVER_DB_NAME }}
            ARCHIVER_DB_HOST:     ${{ secrets.ARCHIVER_DB_HOST }}
            ARCHIVER_DB_USER:     ${{ secrets.ARCHIVER_DB_USER }}
            ARCHIVER_DB_PASSWORD: ${{ secrets.ARCHIVER_DB_PASSWORD }}
            


